const Erros = {
    USUARIO_JA_EXISTE: 'USUARIO_JA_EXISTE',
    USUARIO_NAO_LOCALIZADO: 'USUARIO_NAO_LOCALIZADO',
    CREDENCIAS_NAO_CONFEREM: 'LOGIN_OU_SENHA_INVALIDO',
    SENHA_NAO_CONFERE: 'SENHA_INVALIDO'
}as const

export default Erros